name: Full test harness

on:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: false

jobs:
  regular-tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      # if: github.repository == 'sonos/tract'
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::567805100031:role/github-runner-tract-ci
        aws-region: us-east-2

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-regular-${{steps.date.outputs.date}}-e

          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh

    - name: Full test
      run: .travis/regular-tests.sh

        # - name: Stop sccache server
        #   run: sccache --stop-server || true

  cli-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #      ~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-regular-${{steps.date.outputs.date}}-e

          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh
    - name: Full test 
      env:
        AWS_EC2_METADATA_DISABLED: true
      run: .travis/cli-tests.sh

        #    - name: Stop sccache server
        #      run: sccache --stop-server || true

  examples:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials
      # if: github.repository == 'sonos/tract'
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::567805100031:role/github-runner-tract-ci
        aws-region: us-east-2

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #          ~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-regular-${{steps.date.outputs.date}}-e

          #  - name: "Setup sccache"
          #    run: .travis/setup-sccache.sh

    - name: example tests
      env:
        AWS_EC2_METADATA_DISABLED: true
      run: .travis/examples.sh

        # - name: Stop sccache server
        #   run: sccache --stop-server || true

  onnx-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opset: [1_4_1, 1_5_0, 1_6_0, 1_7_0, 1_8_1, 1_9_0, 1_10_2, 1_11_0, 1_12_0, 1_13_0]

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #      ~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-onnx-${{matrix.opset}}-${{steps.date.outputs.date}}-e
          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh
    - name: Full test
      run: .travis/onnx-tests.sh ${{ matrix.opset }}

        #     - name: Stop sccache server
        #       run: sccache --stop-server || true

  tflite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Full test
      run: .travis/tflite.sh

  onnx-with-asserts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-onnx-with-asserts-${{steps.date.outputs.date}}-e
          #     - name: "Setup sccache"
          #       run: .travis/setup-sccache.sh
    - name: With assertions
      run: |
        rustup update
        cargo -q test -q -p test-onnx-core

        #    - name: Stop sccache server
        #      run: sccache --stop-server || true

  core-paranoid:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-core-paranoid-${{steps.date.outputs.date}}-e
          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh
    - name: Core test with paranoid assertions
      run: |
        rustup update
        cargo test -p tract-core --features paranoid_assertions
        #    - name: Stop sccache server
        #      run: sccache --stop-server || true

  C:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-core-paranoid-${{steps.date.outputs.date}}-e
          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh

    - name: C smoke tests
      run: |
        cd api/c
        cargo install cbindgen
        make
        #    - name: Stop sccache server
        #      run: sccache --stop-server || true

  python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: |
          ~/.rustup
          ~/.cargo/registry
          ~/.cargo/git
          #~/.cache/sccache
          target
          .cached
        key: ${{ runner.os }}-full-core-paranoid-${{steps.date.outputs.date}}-e
          #    - name: "Setup sccache"
          #      run: .travis/setup-sccache.sh

    - name: Pytest bindings
      run: |
        sudo apt-get install -y python3-virtualenv
        cd api/py
        virtualenv venv
        . venv/bin/activate
        pip install -r requirements.txt
        python setup.py install
        pip install pytest
        pytest .
        #    - name: Stop sccache server
        #      run: sccache --stop-server || true
